---
# PodDisruptionBudget for squadcast-helm
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "squadcast-helm.fullname" . }}
  labels:
    {{- include "squadcast-helm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "squadcast-helm.selectorLabels" . | nindent 6 }}
{{- end }}