apiVersion: v1
kind: Service
metadata:
  name: {{ include "squadcast-helm.fullname" . }}
  labels:
    {{- include "squadcast-helm.labels" . | nindent 4 }}
  annotations:
    {{- include "squadcast-helm.annotations" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: web
    {{- if .Values.service.additionalPorts }}
    {{- range $servicePort := .Values.service.additionalPorts }}
    - name: {{ $servicePort.name }}
      port: {{ $servicePort.port }} 
      {{- if $servicePort.protocol }}
      protocol: {{ $servicePort.protocol | default "TCP" }} 
      {{- end }}
      targetPort: {{ $servicePort.targetPort }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "squadcast-helm.selectorLabels" . | nindent 4 }}

