apiVersion: v1
kind: Service
metadata:
  name: {{ include "squadcast-helm.fullname" . }}
  labels:
    # {{- include "squadcast-helm.labels" . | nindent 4 }} FIXME: Uncomment it
    run: {{ include "squadcast-helm.fullname" . }} # FIXME: uncomment it {{- include "squadcast-helm.selectorLabels" . | nindent 8 }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    run: {{ include "squadcast-helm.fullname" . }} # FIXME: uncomment it {{- include "squadcast-helm.selectorLabels" . | nindent 4 }}
